// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Registers API ────────────────────────────────────────

// GetAll calls GET /api/registers/all
func (c *Client) GetAll() (map[string]any, error) {
    return doGET[map[string]any](c, "/api/registers/all", nil)
}

// GetFlags calls GET /api/registers/flags
func (c *Client) GetFlags() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/registers/flags", nil)
}

// GetAvx512 calls GET /api/registers/avx512
func (c *Client) GetAvx512() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/registers/avx512", nil)
}

// GetSpecific calls GET /api/registers/get
func (c *Client) GetSpecific(name string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/registers/get", map[string]string{
        "name": name,
    })
}

// SetReg calls POST /api/registers/set
func (c *Client) SetReg(req struct{Name string `json:"name"`; Value string `json:"value"`}) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/registers/set", req)
}
