// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Modules API ────────────────────────────────────────

// ListModules calls GET /api/modules/list
func (c *Client) ListModules() (ModuleList, error) {
    return doGET[ModuleList](c, "/api/modules/list", nil)
}

// GetInfo calls GET /api/modules/get
func (c *Client) GetInfo(name string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/modules/get", map[string]string{
        "name": name,
    })
}

// GetBase calls GET /api/modules/base
func (c *Client) GetBase(name string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/modules/base", map[string]string{
        "name": name,
    })
}

// GetSection calls GET /api/modules/section
func (c *Client) GetSection(address string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/modules/section", map[string]string{
        "address": address,
    })
}

// GetParty calls GET /api/modules/party
func (c *Client) GetParty(base string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/modules/party", map[string]string{
        "base": base,
    })
}
