// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Memory API ────────────────────────────────────────

// Read calls GET /api/memory/read
func (c *Client) Read(address string, size string) (MemoryReadData, error) {
    return doGET[MemoryReadData](c, "/api/memory/read", map[string]string{
        "address": address,
        "size": size,
    })
}

// Write calls POST /api/memory/write
func (c *Client) Write(req struct{Address string `json:"address"`; Bytes string `json:"bytes"`; Verify bool `json:"verify,omitempty"`}) (MemoryWriteData, error) {
    return doPOST[MemoryWriteData](c, "/api/memory/write", req)
}

// PageInfo calls GET /api/memory/page_info
func (c *Client) PageInfo(address string) (PageInfo, error) {
    return doGET[PageInfo](c, "/api/memory/page_info", map[string]string{
        "address": address,
    })
}

// IsValid calls GET /api/memory/is_valid
func (c *Client) IsValid(address string) (MemoryValid, error) {
    return doGET[MemoryValid](c, "/api/memory/is_valid", map[string]string{
        "address": address,
    })
}

// IsCode calls GET /api/memory/is_code
func (c *Client) IsCode(address string) (MemoryValid, error) {
    return doGET[MemoryValid](c, "/api/memory/is_code", map[string]string{
        "address": address,
    })
}

// Allocate calls POST /api/memory/allocate
func (c *Client) Allocate(Size string) (MemoryAlloc, error) {
    return doPOST[MemoryAlloc](c, "/api/memory/allocate", map[string]any{"size": Size})
}

// Free calls POST /api/memory/free
func (c *Client) Free(Address string) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/memory/free", map[string]any{"address": Address})
}

// Protect calls POST /api/memory/protect
func (c *Client) Protect(req struct{Address string `json:"address"`; Size string `json:"size"`; Protection string `json:"protection"`}) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/memory/protect", req)
}

// UpdateMap calls POST /api/memory/update_map
func (c *Client) UpdateMap() (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/memory/update_map", nil)
}
