// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Command API ────────────────────────────────────────

// Execute calls POST /api/command/exec
func (c *Client) Execute(Command string) (CommandResult, error) {
    return doPOST[CommandResult](c, "/api/command/exec", map[string]any{"command": Command})
}

// Script calls POST /api/command/script
func (c *Client) Script(Commands []string) (CommandResult, error) {
    return doPOST[CommandResult](c, "/api/command/script", map[string]any{"commands": Commands})
}

// Evaluate calls POST /api/command/eval
func (c *Client) Evaluate(Expression string) (EvalResult, error) {
    return doPOST[EvalResult](c, "/api/command/eval", map[string]any{"expression": Expression})
}

// Format calls POST /api/command/format
func (c *Client) Format(Format string) (FormatResult, error) {
    return doPOST[FormatResult](c, "/api/command/format", map[string]any{"format": Format})
}

// SetInitScript calls POST /api/command/init_script
func (c *Client) SetInitScript(File string) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/command/init_script", map[string]any{"file": File})
}

// GetInitScript calls GET /api/command/init_script
func (c *Client) GetInitScript() (StatusMsg, error) {
    return doGET[StatusMsg](c, "/api/command/init_script", nil)
}

// GetHash calls GET /api/command/hash
func (c *Client) GetHash() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/command/hash", nil)
}

// GetEvents calls GET /api/command/events
func (c *Client) GetEvents() (EventsResult, error) {
    return doGET[EventsResult](c, "/api/command/events", nil)
}
