// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Process API ────────────────────────────────────────

// BasicInfo calls GET /api/process/info
func (c *Client) BasicInfo() (ProcessBasicInfo, error) {
    return doGET[ProcessBasicInfo](c, "/api/process/info", nil)
}

// Detailed calls GET /api/process/details
func (c *Client) Detailed() (ProcessDetails, error) {
    return doGET[ProcessDetails](c, "/api/process/details", nil)
}

// Cmdline calls GET /api/process/cmdline
func (c *Client) Cmdline() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/process/cmdline", nil)
}

// Elevated calls GET /api/process/elevated
func (c *Client) Elevated() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/process/elevated", nil)
}

// Dbversion calls GET /api/process/dbversion
func (c *Client) Dbversion() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/process/dbversion", nil)
}

// SetCmdline calls POST /api/process/set_cmdline
func (c *Client) SetCmdline(Cmdline string) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/process/set_cmdline", map[string]any{"cmdline": Cmdline})
}
