// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Disassembly API ────────────────────────────────────────

// AtAddress calls GET /api/disasm/at
func (c *Client) AtAddress(address string, count string) (DisasmResult, error) {
    return doGET[DisasmResult](c, "/api/disasm/at", map[string]string{
        "address": address,
        "count": count,
    })
}

// DisasmFunc calls GET /api/disasm/function
func (c *Client) DisasmFunc(address string, max_instructions string) (DisasmFunctionResult, error) {
    return doGET[DisasmFunctionResult](c, "/api/disasm/function", map[string]string{
        "address": address,
        "max_instructions": max_instructions,
    })
}

// DisasmBasicInfo calls GET /api/disasm/basic
func (c *Client) DisasmBasicInfo(address string) (DisasmBasicInfo, error) {
    return doGET[DisasmBasicInfo](c, "/api/disasm/basic", map[string]string{
        "address": address,
    })
}

// Assemble calls POST /api/disasm/assemble
func (c *Client) Assemble(req DisasmAssembleReq) (AssembleResult, error) {
    return doPOST[AssembleResult](c, "/api/disasm/assemble", req)
}
