// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// Health checks the plugin connectivity.
func (c *Client) Health() (HealthData, error) {
    return doGET[HealthData](c, "/api/health", nil)
}
