// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── AddressConvert API ────────────────────────────────────────

// VaToFile calls GET /api/analysis/va_to_file
func (c *Client) VaToFile(address string) (map[string]any, error) {
    return doGET[map[string]any](c, "/api/analysis/va_to_file", map[string]string{
        "address": address,
    })
}

// FileToVa calls GET /api/analysis/file_to_va
func (c *Client) FileToVa(module string, offset string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/analysis/file_to_va", map[string]string{
        "module": module,
        "offset": offset,
    })
}
