// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Debug API ────────────────────────────────────────

// Run calls POST /api/debug/run
func (c *Client) Run() (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/debug/run", nil)
}

// Pause calls POST /api/debug/pause
func (c *Client) Pause() (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/debug/pause", nil)
}

// ForcePause calls POST /api/debug/force_pause
func (c *Client) ForcePause() (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/debug/force_pause", nil)
}

// GetState calls GET /api/debug/state
func (c *Client) GetState() (DebugState, error) {
    return doGET[DebugState](c, "/api/debug/state", nil)
}

// StepInto calls POST /api/debug/step_into
func (c *Client) StepInto() (StepResult, error) {
    return doPOST[StepResult](c, "/api/debug/step_into", nil)
}

// StepOver calls POST /api/debug/step_over
func (c *Client) StepOver() (StepResult, error) {
    return doPOST[StepResult](c, "/api/debug/step_over", nil)
}

// StepOut calls POST /api/debug/step_out
func (c *Client) StepOut() (StepResult, error) {
    return doPOST[StepResult](c, "/api/debug/step_out", nil)
}

// StopDebug calls POST /api/debug/stop
func (c *Client) StopDebug() (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/debug/stop", nil)
}

// RestartDebug calls POST /api/debug/restart
func (c *Client) RestartDebug() (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/debug/restart", nil)
}

// RunToAddress calls POST /api/debug/run_to
func (c *Client) RunToAddress(Address string) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/debug/run_to", map[string]any{"address": Address})
}
