// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Search API ────────────────────────────────────────

// Pattern calls POST /api/search/pattern
func (c *Client) Pattern(req SearchPatternReq) (PatternResult, error) {
    return doPOST[PatternResult](c, "/api/search/pattern", req)
}

// SearchString calls POST /api/search/string
func (c *Client) SearchString(req SearchStringReq) (StringSearchResult, error) {
    return doPOST[StringSearchResult](c, "/api/search/string", req)
}

// StringAt calls GET /api/search/string_at
func (c *Client) StringAt(address string, encoding string, max_length string) (StringAtResult, error) {
    return doGET[StringAtResult](c, "/api/search/string_at", map[string]string{
        "address": address,
        "encoding": encoding,
        "max_length": max_length,
    })
}

// SymbolAutoComplete calls POST /api/search/auto_complete
func (c *Client) SymbolAutoComplete(req SearchAutoCompleteReq) (AutoCompleteResult, error) {
    return doPOST[AutoCompleteResult](c, "/api/search/auto_complete", req)
}

// EncodeType calls GET /api/search/encode_type
func (c *Client) EncodeType(address string, size string) (map[string]any, error) {
    return doGET[map[string]any](c, "/api/search/encode_type", map[string]string{
        "address": address,
        "size": size,
    })
}
