// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Patches API ────────────────────────────────────────

// ListPatches calls GET /api/patches/list
func (c *Client) ListPatches() (PatchList, error) {
    return doGET[PatchList](c, "/api/patches/list", nil)
}

// Apply calls POST /api/patches/apply
func (c *Client) Apply(req struct{Address string `json:"address"`; Bytes string `json:"bytes"`}) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/patches/apply", req)
}

// Restore calls POST /api/patches/restore
func (c *Client) Restore(req struct{Address string `json:"address"`}) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/patches/restore", req)
}

// ExportPatch calls POST /api/patches/export
func (c *Client) ExportPatch(req struct{Module string `json:"module,omitempty"`; Path string `json:"path"`}) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/patches/export", req)
}
