// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Stack API ────────────────────────────────────────

// GetCallStack calls GET /api/stack/trace
func (c *Client) GetCallStack(max_depth string) (CallStack, error) {
    return doGET[CallStack](c, "/api/stack/trace", map[string]string{
        "max_depth": max_depth,
    })
}

// ReadStack calls GET /api/stack/read
func (c *Client) ReadStack(address string, size string) (StackReadData, error) {
    return doGET[StackReadData](c, "/api/stack/read", map[string]string{
        "address": address,
        "size": size,
    })
}

// Pointers calls GET /api/stack/pointers
func (c *Client) Pointers() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/stack/pointers", nil)
}

// SehChain calls GET /api/stack/seh_chain
func (c *Client) SehChain() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/stack/seh_chain", nil)
}

// ReturnAddress calls GET /api/stack/return_address
func (c *Client) ReturnAddress() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/stack/return_address", nil)
}

// StackComment calls GET /api/stack/comment
func (c *Client) StackComment(address string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/stack/comment", map[string]string{
        "address": address,
    })
}
