// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Threads API ────────────────────────────────────────

// ListThreads calls GET /api/threads/list
func (c *Client) ListThreads() (ThreadList, error) {
    return doGET[ThreadList](c, "/api/threads/list", nil)
}

// Current calls GET /api/threads/current
func (c *Client) Current() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/threads/current", nil)
}

// Count calls GET /api/threads/count
func (c *Client) Count() (ThreadCount, error) {
    return doGET[ThreadCount](c, "/api/threads/count", nil)
}

// GetThread calls GET /api/threads/get
func (c *Client) GetThread(id string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/threads/get", map[string]string{
        "id": id,
    })
}

// ThreadTeb calls GET /api/threads/teb
func (c *Client) ThreadTeb(tid string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/threads/teb", map[string]string{
        "tid": tid,
    })
}

// ThreadName calls GET /api/threads/name
func (c *Client) ThreadName(tid string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/threads/name", map[string]string{
        "tid": tid,
    })
}

// Switch calls POST /api/threads/switch
func (c *Client) Switch(req IdReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/threads/switch", req)
}

// Suspend calls POST /api/threads/suspend
func (c *Client) Suspend(req IdReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/threads/suspend", req)
}

// Resume calls POST /api/threads/resume
func (c *Client) Resume(req IdReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/threads/resume", req)
}
