// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Antidebug API ────────────────────────────────────────

// Peb calls GET /api/antidebug/peb
func (c *Client) Peb(pid string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/antidebug/peb", map[string]string{
        "pid": pid,
    })
}

// Teb calls GET /api/antidebug/teb
func (c *Client) Teb(tid string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/antidebug/teb", map[string]string{
        "tid": tid,
    })
}

// Dep calls GET /api/antidebug/dep_status
func (c *Client) Dep() (map[string]any, error) {
    return doGET[map[string]any](c, "/api/antidebug/dep_status", nil)
}

// HideDebugger calls POST /api/antidebug/hide_debugger
func (c *Client) HideDebugger() (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/antidebug/hide_debugger", nil)
}
