// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Command API ────────────────────────────────────────

// Execute calls POST /api/command/exec
func (c *Client) Execute(req struct{Command string `json:"command"`}) (CommandResult, error) {
    return doPOST[CommandResult](c, "/api/command/exec", req)
}

// Script calls POST /api/command/script
func (c *Client) Script(req struct{Commands []string `json:"commands"`}) (CommandResult, error) {
    return doPOST[CommandResult](c, "/api/command/script", req)
}

// Evaluate calls POST /api/command/eval
func (c *Client) Evaluate(req struct{Expression string `json:"expression"`}) (EvalResult, error) {
    return doPOST[EvalResult](c, "/api/command/eval", req)
}

// Format calls POST /api/command/format
func (c *Client) Format(req struct{Format string `json:"format"`}) (FormatResult, error) {
    return doPOST[FormatResult](c, "/api/command/format", req)
}

// SetInitScript calls POST /api/command/init_script
func (c *Client) SetInitScript(req struct{File string `json:"file"`}) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/command/init_script", req)
}

// GetInitScript calls GET /api/command/init_script
func (c *Client) GetInitScript() (StatusMsg, error) {
    return doGET[StatusMsg](c, "/api/command/init_script", nil)
}

// GetHash calls GET /api/command/hash
func (c *Client) GetHash() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/command/hash", nil)
}

// GetEvents calls GET /api/command/events
func (c *Client) GetEvents() (EventsResult, error) {
    return doGET[EventsResult](c, "/api/command/events", nil)
}
