// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Exceptions API ────────────────────────────────────────

// SetExc calls POST /api/exceptions/set_bp
func (c *Client) SetExc(req struct{Code string `json:"code"`; Chance string `json:"chance"`}) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/exceptions/set_bp", req)
}

// DelExc calls POST /api/exceptions/delete_bp
func (c *Client) DelExc(req struct{Code string `json:"code"`}) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/exceptions/delete_bp", req)
}

// ListExc calls GET /api/exceptions/list_bps
func (c *Client) ListExc() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/exceptions/list_bps", nil)
}

// ListCodes calls GET /api/exceptions/list_codes
func (c *Client) ListCodes() (map[string]any, error) {
    return doGET[map[string]any](c, "/api/exceptions/list_codes", nil)
}

// SkipExc calls POST /api/exceptions/skip
func (c *Client) SkipExc() (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/exceptions/skip", nil)
}
