// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Symbols API ────────────────────────────────────────

// Resolve calls GET /api/symbols/resolve
func (c *Client) Resolve(name string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/symbols/resolve", map[string]string{
        "name": name,
    })
}

// SymAt calls GET /api/symbols/at
func (c *Client) SymAt(address string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/symbols/at", map[string]string{
        "address": address,
    })
}

// SearchSym calls GET /api/symbols/search
func (c *Client) SearchSym(pattern string, module string) (SymbolSearchResult, error) {
    return doGET[SymbolSearchResult](c, "/api/symbols/search", map[string]string{
        "pattern": pattern,
        "module": module,
    })
}

// ListModule calls GET /api/symbols/list
func (c *Client) ListModule(module string) (SymbolList, error) {
    return doGET[SymbolList](c, "/api/symbols/list", map[string]string{
        "module": module,
    })
}

// GetLabel calls GET /api/labels/get
func (c *Client) GetLabel(address string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/labels/get", map[string]string{
        "address": address,
    })
}

// SetLabel calls POST /api/labels/set
func (c *Client) SetLabel(req LabelSetReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/labels/set", req)
}

// GetComment calls GET /api/comments/get
func (c *Client) GetComment(address string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/comments/get", map[string]string{
        "address": address,
    })
}

// SetComment calls POST /api/comments/set
func (c *Client) SetComment(req CommentSetReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/comments/set", req)
}

// Bookmark calls POST /api/bookmarks/set
func (c *Client) Bookmark(req BookmarkSetReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/bookmarks/set", req)
}
