// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Dumping API ────────────────────────────────────────

// PeHeader calls GET /api/dump/pe_header
func (c *Client) PeHeader(address string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/dump/pe_header", map[string]string{
        "address": address,
    })
}

// Sections calls GET /api/dump/sections
func (c *Client) Sections(module string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/dump/sections", map[string]string{
        "module": module,
    })
}

// Imports calls GET /api/dump/imports
func (c *Client) Imports(module string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/dump/imports", map[string]string{
        "module": module,
    })
}

// Exports calls GET /api/dump/exports
func (c *Client) Exports(module string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/dump/exports", map[string]string{
        "module": module,
    })
}

// EntryPoint calls GET /api/dump/entry_point
func (c *Client) EntryPoint(module string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/dump/entry_point", map[string]string{
        "module": module,
    })
}

// Relocations calls GET /api/dump/relocations
func (c *Client) Relocations(address string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/dump/relocations", map[string]string{
        "address": address,
    })
}

// DumpModule calls POST /api/dump/module
func (c *Client) DumpModule(req struct{Module string `json:"module"`; File string `json:"file"`}) (map[string]string, error) {
    return doPOST[map[string]string](c, "/api/dump/module", req)
}

// FixIat calls POST /api/dump/fix_iat
func (c *Client) FixIat(OEP string) (map[string]string, error) {
    return doPOST[map[string]string](c, "/api/dump/fix_iat", map[string]any{"oep": OEP})
}
