// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Database API ────────────────────────────────────────

// Constants calls GET /api/analysis/constants
func (c *Client) Constants() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/analysis/constants", nil)
}

// ErrorCodes calls GET /api/analysis/error_codes
func (c *Client) ErrorCodes() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/analysis/error_codes", nil)
}

// Structs calls GET /api/analysis/structs
func (c *Client) Structs() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/analysis/structs", nil)
}

// Strings calls GET /api/analysis/strings
func (c *Client) Strings(module string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/analysis/strings", map[string]string{
        "module": module,
    })
}
