// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Tracing API ────────────────────────────────────────

// TraceInto calls POST /api/trace/into
func (c *Client) TraceInto(req TraceIntoReq) (map[string]string, error) {
    return doPOST[map[string]string](c, "/api/trace/into", req)
}

// TraceOver calls POST /api/trace/over
func (c *Client) TraceOver(req TraceOverReq) (map[string]string, error) {
    return doPOST[map[string]string](c, "/api/trace/over", req)
}

// TraceRun calls POST /api/trace/run
func (c *Client) TraceRun(req struct{Party string `json:"party"`}) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/trace/run", req)
}

// TraceStop calls POST /api/trace/stop
func (c *Client) TraceStop() (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/trace/stop", nil)
}

// TraceStatus calls GET /api/trace/status
func (c *Client) TraceStatus() (TraceStatus, error) {
    return doGET[TraceStatus](c, "/api/trace/status", nil)
}

// Animate calls POST /api/trace/animate
func (c *Client) Animate(req struct{Command string `json:"command"`}) (map[string]string, error) {
    return doPOST[map[string]string](c, "/api/trace/animate", req)
}

// ConditionalRun calls POST /api/trace/conditional_run
func (c *Client) ConditionalRun(req TraceConditionalRunReq) (map[string]string, error) {
    return doPOST[map[string]string](c, "/api/trace/conditional_run", req)
}

// LogSetup calls POST /api/trace/log
func (c *Client) LogSetup(req TraceLogReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/trace/log", req)
}

// Hitcount calls GET /api/trace/record/hitcount
func (c *Client) Hitcount(address string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/trace/record/hitcount", map[string]string{
        "address": address,
    })
}

// TraceType calls GET /api/trace/record/type
func (c *Client) TraceType(address string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/trace/record/type", map[string]string{
        "address": address,
    })
}

// SetTraceType calls POST /api/trace/record/set_type
func (c *Client) SetTraceType(req struct{Address string `json:"address"`; Type int `json:"type"`}) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/trace/record/set_type", req)
}
