// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Analysis API ────────────────────────────────────────

// Function calls GET /api/analysis/function
func (c *Client) Function(address string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/analysis/function", map[string]string{
        "address": address,
    })
}

// XrefsTo calls GET /api/analysis/xrefs_to
func (c *Client) XrefsTo(address string) (XrefList, error) {
    return doGET[XrefList](c, "/api/analysis/xrefs_to", map[string]string{
        "address": address,
    })
}

// XrefsFrom calls GET /api/analysis/xrefs_from
func (c *Client) XrefsFrom(address string) (XrefList, error) {
    return doGET[XrefList](c, "/api/analysis/xrefs_from", map[string]string{
        "address": address,
    })
}

// BasicBlocks calls GET /api/analysis/basic_blocks
func (c *Client) BasicBlocks(address string) (BasicBlockList, error) {
    return doGET[BasicBlockList](c, "/api/analysis/basic_blocks", map[string]string{
        "address": address,
    })
}

// Source calls GET /api/analysis/source
func (c *Client) Source(address string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/analysis/source", map[string]string{
        "address": address,
    })
}

// MnemonicBrief calls GET /api/analysis/mnemonic_brief
func (c *Client) MnemonicBrief(mnemonic string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/analysis/mnemonic_brief", map[string]string{
        "mnemonic": mnemonic,
    })
}
