// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Breakpoints API ────────────────────────────────────────

// SetSoftware calls POST /api/breakpoints/set
func (c *Client) SetSoftware(req BpSetSoftwareReq) (BpSetData, error) {
    return doPOST[BpSetData](c, "/api/breakpoints/set", req)
}

// SetHardware calls POST /api/breakpoints/set_hardware
func (c *Client) SetHardware(req BpSetHardwareReq) (BpSetData, error) {
    return doPOST[BpSetData](c, "/api/breakpoints/set_hardware", req)
}

// SetMemory calls POST /api/breakpoints/set_memory
func (c *Client) SetMemory(req BpSetMemoryReq) (BpSetData, error) {
    return doPOST[BpSetData](c, "/api/breakpoints/set_memory", req)
}

// BpDelete calls POST /api/breakpoints/delete
func (c *Client) BpDelete(req BpDeleteReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/breakpoints/delete", req)
}

// Enable calls POST /api/breakpoints/enable
func (c *Client) Enable(req BpAddrReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/breakpoints/enable", req)
}

// Disable calls POST /api/breakpoints/disable
func (c *Client) Disable(req BpAddrReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/breakpoints/disable", req)
}

// Toggle calls POST /api/breakpoints/toggle
func (c *Client) Toggle(req BpAddrReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/breakpoints/toggle", req)
}

// SetCondition calls POST /api/breakpoints/set_condition
func (c *Client) SetCondition(req BpConditionReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/breakpoints/set_condition", req)
}

// SetLog calls POST /api/breakpoints/set_log
func (c *Client) SetLog(req BpLogReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/breakpoints/set_log", req)
}

// ResetHitCount calls POST /api/breakpoints/reset_hit_count
func (c *Client) ResetHitCount(req BpAddrReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/breakpoints/reset_hit_count", req)
}

// GetBp calls GET /api/breakpoints/get
func (c *Client) GetBp(address string) (BpItem, error) {
    return doGET[BpItem](c, "/api/breakpoints/get", map[string]string{
        "address": address,
    })
}

// ListBps calls GET /api/breakpoints/list
func (c *Client) ListBps() (BpListData, error) {
    return doGET[BpListData](c, "/api/breakpoints/list", nil)
}

// ConfigureBp calls POST /api/breakpoints/configure
func (c *Client) ConfigureBp(req BpConfigureReq) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/breakpoints/configure", req)
}
