// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Controlflow API ────────────────────────────────────────

// Cfg calls GET /api/cfg/function
func (c *Client) Cfg(address string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/cfg/function", map[string]string{
        "address": address,
    })
}

// BranchDest calls GET /api/cfg/branch_dest
func (c *Client) BranchDest(address string) (map[string]any, error) {
    return doGET[map[string]any](c, "/api/cfg/branch_dest", map[string]string{
        "address": address,
    })
}

// IsJumpTaken calls GET /api/cfg/is_jump_taken
func (c *Client) IsJumpTaken(address string) (map[string]any, error) {
    return doGET[map[string]any](c, "/api/cfg/is_jump_taken", map[string]string{
        "address": address,
    })
}

// Loops calls GET /api/cfg/loops
func (c *Client) Loops(address string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/cfg/loops", map[string]string{
        "address": address,
    })
}

// FuncType calls GET /api/cfg/func_type
func (c *Client) FuncType(address string) (map[string]any, error) {
    return doGET[map[string]any](c, "/api/cfg/func_type", map[string]string{
        "address": address,
    })
}

// AddFunction calls POST /api/cfg/add_function
func (c *Client) AddFunction(req struct{Start string `json:"start"`; End string `json:"end"`}) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/cfg/add_function", req)
}

// DeleteFunction calls POST /api/cfg/delete_function
func (c *Client) DeleteFunction(req struct{Address string `json:"address"`}) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/cfg/delete_function", req)
}
