// Code generated by gen_go.py - DO NOT EDIT.
package servergo

// ─── Handles API ────────────────────────────────────────

// ListHandles calls GET /api/handles/list
func (c *Client) ListHandles() (HandleList, error) {
    return doGET[HandleList](c, "/api/handles/list", nil)
}

// ListTcp calls GET /api/handles/tcp
func (c *Client) ListTcp() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/handles/tcp", nil)
}

// ListWindows calls GET /api/handles/windows
func (c *Client) ListWindows() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/handles/windows", nil)
}

// ListHeaps calls GET /api/handles/heaps
func (c *Client) ListHeaps() (map[string]string, error) {
    return doGET[map[string]string](c, "/api/handles/heaps", nil)
}

// GetName calls GET /api/handles/get
func (c *Client) GetName(handle string) (map[string]string, error) {
    return doGET[map[string]string](c, "/api/handles/get", map[string]string{
        "handle": handle,
    })
}

// CloseHandle calls POST /api/handles/close
func (c *Client) CloseHandle(req struct{Handle string `json:"handle"`}) (StatusMsg, error) {
    return doPOST[StatusMsg](c, "/api/handles/close", req)
}
