// Code generated by gen_go.py - DO NOT EDIT.
package servergo

import (
    "bytes"
    "encoding/json"
    "fmt"
    "io"
    "net/http"
    "time"
)

// Client is the HTTP client for the x64dbg MCP plugin REST API.
type Client struct {
    baseURL    string
    httpClient *http.Client
    token      string
}

// NewClient creates a new Client with default settings.
func NewClient(host string, port int, token string) *Client {
    if host == "" { host = "127.0.0.1" }
    if port == 0  { port = 27042 }
    return &Client{
        baseURL:    fmt.Sprintf("http://%s:%d", host, port),
        httpClient: &http.Client{Timeout: 30 * time.Second},
        token:      token,
    }
}

// SetTimeout changes the HTTP client timeout (0 = no timeout).
func (c *Client) SetTimeout(d time.Duration) { c.httpClient.Timeout = d }

func doGET[T any](c *Client, path string, params map[string]string) (T, error) {
    var zero T
    reqURL := c.baseURL + path
    if len(params) > 0 {
        reqURL += "?"
        for k, v := range params {
            if v != "" { reqURL += fmt.Sprintf("%s=%s&", k, v) }
        }
        reqURL = reqURL[:len(reqURL)-1]
    }
    req, err := http.NewRequest("GET", reqURL, nil)
    if err != nil { return zero, fmt.Errorf("NewRequest: %w", err) }
    if c.token != "" { req.Header.Set("Authorization", "Bearer "+c.token) }
    resp, err := c.httpClient.Do(req)
    if err != nil { return zero, fmt.Errorf("http.Do: %w", err) }
    defer resp.Body.Close()
    return parseEnvelope[T](resp)
}

func doPOST[T any](c *Client, path string, body any) (T, error) {
    var zero T
    var bodyReader io.Reader
    if body != nil {
        b, err := json.Marshal(body)
        if err != nil { return zero, fmt.Errorf("json.Marshal: %w", err) }
        bodyReader = bytes.NewReader(b)
    }
    req, err := http.NewRequest("POST", c.baseURL+path, bodyReader)
    if err != nil { return zero, fmt.Errorf("NewRequest: %w", err) }
    if body != nil { req.Header.Set("Content-Type", "application/json") }
    if c.token != "" { req.Header.Set("Authorization", "Bearer "+c.token) }
    resp, err := c.httpClient.Do(req)
    if err != nil { return zero, fmt.Errorf("http.Do: %w", err) }
    defer resp.Body.Close()
    return parseEnvelope[T](resp)
}

func parseEnvelope[T any](resp *http.Response) (T, error) {
    var zero T
    raw, err := io.ReadAll(resp.Body)
    if err != nil { return zero, fmt.Errorf("read body: %w", err) }
    var env struct {
        Success bool             `json:"success"`
        Data    json.RawMessage  `json:"data"`
        Error   *struct {
            Code    int    `json:"code"`
            Message string `json:"message"`
        } `json:"error,omitempty"`
    }
    if err := json.Unmarshal(raw, &env); err != nil {
        return zero, fmt.Errorf("json.Unmarshal envelope: %w (body: %s)", err, string(raw))
    }
    if !env.Success {
        code, msg := 0, "unknown error"
        if env.Error != nil { code = env.Error.Code; msg = env.Error.Message }
        return zero, fmt.Errorf("plugin error (%d): %s", code, msg)
    }
    var data T
    if len(env.Data) > 0 {
        if err := json.Unmarshal(env.Data, &data); err != nil {
            return zero, fmt.Errorf("json.Unmarshal data: %w (body: %s)", err, string(env.Data))
        }
    }
    return data, nil
}
