// Code generated by gen_go.py - DO NOT EDIT.
package servergo

type BpAddrReq struct {
    Address string `json:"address"`
}

type BpSetSoftwareReq struct {
    Address    string `json:"address"`
    Singleshot bool   `json:"singleshot,omitempty"`
}

type BpSetHardwareReq struct {
    Address string `json:"address"`
    Type    string `json:"type,omitempty"`
    Size    string `json:"size,omitempty"`
}

type BpSetMemoryReq struct {
    Address string `json:"address"`
    Type    string `json:"type,omitempty"`
}

type BpDeleteReq struct {
    Address string `json:"address"`
    Type    string `json:"type,omitempty"`
}

type BpConditionReq struct {
    Address   string `json:"address"`
    Condition string `json:"condition"`
}

type BpLogReq struct {
    Address string `json:"address"`
    Text    string `json:"text"`
}

type BpConfigureReq struct{}

type DisasmAssembleReq struct {
    Address     string `json:"address"`
    Instruction string `json:"instruction"`
}

type LabelSetReq struct {
    Address string `json:"address"`
    Text    string `json:"text"`
}

type CommentSetReq struct {
    Address string `json:"address"`
    Text    string `json:"text"`
}

type BookmarkSetReq struct {
    Address string `json:"address"`
    Set     bool   `json:"set"`
}

type SearchPatternReq struct {
    Pattern    string `json:"pattern"`
    Address    string `json:"address,omitempty"`
    Size       string `json:"size,omitempty"`
    MaxResults int    `json:"max_results,omitempty"`
}

type SearchStringReq struct {
    Text     string `json:"text"`
    Module   string `json:"module,omitempty"`
    Encoding string `json:"encoding,omitempty"`
}

type SearchAutoCompleteReq struct {
    Search     string `json:"search"`
    MaxResults int    `json:"max_results,omitempty"`
}

type TraceIntoReq struct {
    Condition string `json:"condition,omitempty"`
    MaxSteps  string `json:"max_steps,omitempty"`
    LogText   string `json:"log_text,omitempty"`
}

type TraceOverReq struct {
    Condition string `json:"condition,omitempty"`
    MaxSteps  string `json:"max_steps,omitempty"`
    LogText   string `json:"log_text,omitempty"`
}

type TraceConditionalRunReq struct {
    Type              string `json:"type,omitempty"`
    BreakCondition    string `json:"break_condition,omitempty"`
    LogText           string `json:"log_text,omitempty"`
    LogCondition      string `json:"log_condition,omitempty"`
    CommandText       string `json:"command_text,omitempty"`
    CommandCondition  string `json:"command_condition,omitempty"`
}

type TraceLogReq struct {
    File      string `json:"file"`
    Text      string `json:"text,omitempty"`
    Condition string `json:"condition,omitempty"`
}

type IdReq struct {
    ID string `json:"id"`
}
