// Code generated by gen_go.py - DO NOT EDIT.
package servergo

import "encoding/json"

type Envelope struct {
    Success bool             `json:"success"`
    Data    json.RawMessage  `json:"data,omitempty"`
    Error   *struct {
        Code    int    `json:"code"`
        Message string `json:"message"`
    } `json:"error,omitempty"`
}

type StatusMsg struct {
    Message string `json:"message,omitempty"`
}

type StepResult struct {
    CIP     string `json:"cip,omitempty"`
    Message string `json:"message,omitempty"`
}

type DebugState struct {
    CIP    string `json:"cip,omitempty"`
    State  string `json:"state"`
    Module string `json:"module,omitempty"`
    Label  string `json:"label,omitempty"`
}

type MemoryReadData struct {
    Address string `json:"address"`
    Size    int    `json:"size"`
    Hex     string `json:"hex"`
    ASCII   string `json:"ascii"`
}

type MemoryWriteData struct {
    Address      string `json:"address"`
    BytesWritten int    `json:"bytes_written"`
    Verified     bool   `json:"verified,omitempty"`
    VerifyError  string `json:"verify_error,omitempty"`
}

type MemoryValid struct {
    Address string `json:"address"`
    Valid   bool   `json:"valid"`
}

type MemoryAlloc struct {
    Address string `json:"address"`
    Size    string `json:"size"`
}

type PageInfo struct {
    Address    string `json:"address"`
    Size       string `json:"size"`
    Protection string `json:"protection"`
    State      string `json:"state"`
    Type       string `json:"type"`
}

type MemMapEntry struct {
    Address    string `json:"address"`
    Size       string `json:"size"`
    Protection string `json:"protection"`
    State      string `json:"state"`
    Type       string `json:"type"`
    Info       string `json:"info,omitempty"`
    Module     string `json:"module,omitempty"`
    Section    string `json:"section,omitempty"`
}

type MemMapList struct {
    Map   []MemMapEntry `json:"map"`
    Count int           `json:"count"`
}

type BpItem struct {
    Address          string `json:"address"`
    Enabled          bool   `json:"enabled"`
    Active           bool   `json:"active"`
    Singleshot       bool   `json:"singleshoot"`
    Name             string `json:"name"`
    Module           string `json:"module"`
    HitCount         int    `json:"hit_count"`
    FastResume       bool   `json:"fast_resume"`
    Silent           bool   `json:"silent"`
    BreakCondition   string `json:"break_condition"`
    CommandCondition string `json:"command_condition"`
    CommandText      string `json:"command_text"`
    LogText          string `json:"log_text"`
    LogCondition     string `json:"log_condition"`
    Type             int    `json:"type"`
    TypeName         string `json:"type_name"`
    Label            string `json:"label,omitempty"`
}

type BpListData struct {
    Breakpoints []BpItem `json:"breakpoints"`
    Count       int      `json:"count"`
}

type BpSetData struct {
    Address    string `json:"address"`
    Type       string `json:"type"`
    Singleshot bool   `json:"singleshot,omitempty"`
}

type InstrInfo struct {
    Address  string `json:"address"`
    Mnemonic string `json:"mnemonic"`
    Op       string `json:"op"`
    Bytes    string `json:"bytes"`
    Size     int    `json:"size"`
    Comment  string `json:"comment,omitempty"`
}

type DisasmResult struct {
    Address      string      `json:"address"`
    Count        int         `json:"count"`
    Instructions []InstrInfo `json:"instructions"`
}

type DisasmFunctionResult struct {
    Address       string      `json:"address"`
    Instructions  []InstrInfo `json:"instructions,omitempty"`
    Note          string      `json:"note,omitempty"`
    FallbackCount int         `json:"fallback_count,omitempty"`
}

type DisasmBasicInfo struct {
    Address string `json:"address,omitempty"`
    Size    int    `json:"size,omitempty"`
    Branch  bool   `json:"branch,omitempty"`
    Call    bool   `json:"call,omitempty"`
}

type AssembleResult struct {
    Size  int    `json:"size"`
    Bytes string `json:"bytes"`
}

type CallStackEntry struct {
    Address string `json:"address"`
    To      string `json:"to,omitempty"`
    From    string `json:"from,omitempty"`
    Comment string `json:"comment,omitempty"`
}

type CallStack struct {
    Stack []CallStackEntry `json:"stack"`
    Count int              `json:"count"`
}

type StackReadData struct {
    Address string `json:"address"`
    Size    int    `json:"size"`
    Hex     string `json:"hex"`
    ASCII   string `json:"ascii"`
}

type ModuleInfoData struct {
    Name         string `json:"name"`
    Base         string `json:"base"`
    Size         int    `json:"size"`
    Entry        string `json:"entry"`
    SectionCount int    `json:"sectionCount"`
    Path         string `json:"path"`
}

type ModuleList struct {
    Modules []ModuleInfoData `json:"modules"`
    Count   int              `json:"count"`
}

type SymbolEntry struct {
    Address     string `json:"address"`
    Decorated   string `json:"decorated"`
    Undecorated string `json:"undecorated"`
}

type SymbolList struct {
    Symbols []SymbolEntry `json:"symbols"`
}

type SymbolSearchResult struct {
    Symbols []SymbolEntry `json:"symbols,omitempty"`
}

type CommandResult struct {
    Output string `json:"output"`
}

type EvalResult struct {
    Value string `json:"value"`
}

type FormatResult struct {
    Result string `json:"result"`
}

type EventsResult struct {
    Events []string `json:"events"`
}

type ProcessBasicInfo struct {
    PID           int    `json:"pid"`
    PEBAddress    string `json:"peb_address"`
    EntryPoint    string `json:"entry_point"`
    DebuggerState string `json:"debugger_state"`
}

type ProcessDetails struct {
    PID           int    `json:"pid"`
    PEBAddress    string `json:"peb_address"`
    EntryPoint    string `json:"entry_point"`
    DebuggerState string `json:"debugger_state"`
    IsElevated    bool   `json:"is_elevated"`
    DepEnabled    bool   `json:"dep_enabled"`
}

type ThreadEntry struct {
    ID     int    `json:"id,omitempty"`
    Name   string `json:"name,omitempty"`
    Handle string `json:"handle,omitempty"`
    TEB    string `json:"teb,omitempty"`
    Entry  string `json:"entry,omitempty"`
}

type ThreadList struct {
    Threads []ThreadEntry `json:"threads"`
    Count   int           `json:"count"`
}

type ThreadCount struct {
    Count int `json:"count"`
}

type HandleInfo struct {
    Handle string `json:"handle"`
    Type   string `json:"type"`
    Name   string `json:"name,omitempty"`
}

type HandleList struct {
    Handles []HandleInfo `json:"handles"`
    Count   int          `json:"count"`
}

type SearchHit struct {
    Address string `json:"address"`
    Data    string `json:"data,omitempty"`
}

type PatternResult struct {
    Hits         []SearchHit `json:"hits"`
    Count        int         `json:"count"`
    TotalMatches int         `json:"total_matches"`
}

type StringSearchResult struct {
    Hits  []SearchHit `json:"hits"`
    Count int         `json:"count"`
}

type StringAtResult struct {
    Address string `json:"address"`
    String  string `json:"string"`
}

type AutoCompleteResult struct {
    Suggestions []string `json:"suggestions"`
}

type XrefEntry struct {
    Address string `json:"address"`
    Type    string `json:"type,omitempty"`
}

type XrefList struct {
    Xrefs []XrefEntry `json:"xrefs"`
}

type BasicBlockEntry struct {
    Start string `json:"start"`
    End   string `json:"end"`
}

type BasicBlockList struct {
    Blocks []BasicBlockEntry `json:"blocks"`
}

type TraceStatus struct {
    Tracing bool   `json:"tracing,omitempty"`
    File    string `json:"file,omitempty"`
}

type PatchEntry struct {
    Address string `json:"address"`
    Old     string `json:"old"`
    New     string `json:"new"`
}

type PatchList struct {
    Patches []PatchEntry `json:"patches"`
    Count   int          `json:"count"`
}

type HealthData struct {
    Version string `json:"version"`
    Plugin  string `json:"plugin"`
    Status  string `json:"status"`
}
